import numpy as np

def get_the_saw():
    """
    Synthetic example. Returns a saw tooth wave. 
    """
    return np.fromiter( (x%100 for x in range(1,5000)) , int )

def collatz_sequence(seq, x):
    """
    Helper for Collatz fn. immediately below. 
    """
    seq.append(x)
    if x == 1:
        return seq
    x = x/2 if (x % 2 == 0)  else x*3+1
    return collatz_sequence(seq, x)


def get_the_collatz(x=63728127):
    """
    Synthetic exampe. Returns consecutive intermediate values
    generated by following a particular path of the Collatz conjecture
    """
    seq = []
    seq = collatz_sequence(seq, x)
    return np.asarray(seq)

